export const ROUTE_ROOT = '/'
export const ROUTE_HOME = '/time-tracker'
export const ROUTE_LOG = '/log'
export const ROUTE_CHART = '/chart'
export const ROUTE_TASK = '/task/:id'
export const ROUTE_NOT_FOUND = '/not-found'
